#!/bin/bash

# number of days to keep old jobs scratch directories
DAYS=7
DIR=/share/opal/meme

files=`find $DIR  -type d -mtime +$DAYS -mindepth 1 -print`
for i in $files;
do
        rm -rf $i
done

