#!/bin/bash

# Remove tomtom temp files from MEME jobs

clean_temp_files () {
    DAYS=3  
    DIR=$1
    NAME=$2
    if [ -d $DIR ] ; then
        files=`find $DIR  -type f -mtime +$DAYS -name '$NAME'  -print`
        for i in $files;
        do
            rm -rf $i
        done
    fi
}

clean_temp_files /opt/tomcat/temp CGItemp\*
clean_temp_files /opt/tomcat/temp \*_seq_\* 
clean_temp_files /opt/tomcat/temp stderr_\* 

